import type { Metadata } from "next";
import Header from "../_components/header";
import Sidebar from "../_components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: any;
}) {
  return (
    <div>
      <Sidebar />
      <Header />
      <div className="bg-gray-100 m-5 w-[87%] h-[90%] absolute rounded-lg  left-[1%]">
      {children}
      </div>
   
    </div>
  );
}
